name: Build Kahilapan apk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # ← INI YANG HARUS DITAMBAHKAN
    inputs:
      buildType:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup
      run: |
         chmod +x gradlew
         chmod +x generate_keystore.sh
         ./generate_keystore.sh
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Build Release APK
      run: ./gradlew assembleRelease
    
    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kahilapan
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
    
    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
        generate_release_notes: true